[project]
name = "wallet-ap"
version = "0.1.0"
authors = [
    {name = "Elena Dobruk", email = "elena.dobruk@yandex.ru"},
]
description = "A compact wallet API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "flake8>=7.1.2",
]
